# Generated by Django 4.1.7 on 2023-03-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asterism",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asterism_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Constellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("constellation_name", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="Culture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("culture_name", models.CharField(max_length=200)),
                ("geographic_region", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="StarSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star_hd", models.IntegerField()),
                ("star_proper_name", models.CharField(max_length=200)),
                (
                    "asterism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="asterisms.asterism",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Star",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star_name", models.CharField(default="none", max_length=200)),
                ("star_hd", models.IntegerField(default=0)),
                (
                    "constellation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="asterisms.constellation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asterism",
            name="culture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="asterisms.culture"
            ),
        ),
    ]
