# Generated by Django 4.1.7 on 2023-04-03 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("asterisms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star_hip", models.IntegerField()),
                ("star_hd", models.IntegerField(blank=True, null=True)),
                ("star_ra", models.FloatField()),
                ("star_dec", models.FloatField()),
                (
                    "asterisms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="asterisms.asterism",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="star",
            name="constellation",
        ),
        migrations.RemoveField(
            model_name="starsample",
            name="asterism",
        ),
        migrations.AlterField(
            model_name="culture",
            name="geographic_region",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="Constellation",
        ),
        migrations.DeleteModel(
            name="Star",
        ),
        migrations.DeleteModel(
            name="StarSample",
        ),
    ]
