# Generated by Django 4.1.7 on 2023-04-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asterisms", "0002_stars_remove_star_constellation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stars",
            name="star_hd",
        ),
        migrations.AddField(
            model_name="asterism",
            name="asterism_desc",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="asterism",
            name="asterism_img",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="asterism",
            name="asterism_img_2",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="culture",
            name="culture_desc",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="culture",
            name="culture_img",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="culture",
            name="culture_img_2",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
